# Generated by Django 6.0.2 on 2026-02-15 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0002_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='last_taken',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
