# Generated by Django 6.0.2 on 2026-02-22 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0003_medication_last_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='hours_between_doses',
            field=models.IntegerField(default=8),
        ),
    ]
